# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 20:39
from __future__ import unicode_literals

import boh.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boh', '0005_v1_0_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCustomFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A name for this custom field', max_length=64, verbose_name='custom field name')),
                ('description', models.TextField(blank=True, help_text="Information about the custom field's purpose.")),
                ('key', models.CharField(help_text="A unique key for this field. (e.g., 'custom_id')", max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Key must be lowercase with no spaces. Underscores may be used to seperate words.', regex='^[0-9a-z_]+$')])),
                ('validation_regex', models.CharField(blank=True, help_text="A regular expression to validate on save. (e.g. '[0-9]{5}$' is a regex for a number with a length of 5)", max_length=255, validators=[boh.models.CustomField.validate_regex])),
                ('validation_description', models.CharField(blank=True, help_text='A brief description of the validation expression to be shown to users.', max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Custom Fields',
                'verbose_name': 'Custom Field',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='applicationfileupload',
            name='application',
        ),
        migrations.RemoveField(
            model_name='applicationfileupload',
            name='user',
        ),
        migrations.RemoveField(
            model_name='externalrequest',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='externalrequest',
            name='application',
        ),
        migrations.RemoveField(
            model_name='externalrequest',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='requestable',
        ),
        migrations.AddField(
            model_name='application',
            name='asvs_doc_url',
            field=models.URLField(blank=True, help_text='URL to the detailed ASVS assessment.'),
        ),
        migrations.AddField(
            model_name='application',
            name='asvs_level',
            field=models.IntegerField(blank=True, choices=[(None, 'Not Specified'), (0, '0'), (1, '1'), (2, '2'), (3, '3')], help_text='Assessed ASVS Level', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='asvs_level_percent_achieved',
            field=models.PositiveIntegerField(blank=True, help_text='Percent compliant to the targeted ASVS level.', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='asvs_level_target',
            field=models.IntegerField(blank=True, choices=[(None, 'Not Specified'), (0, '0'), (1, '1'), (2, '2'), (3, '3')], help_text='Targeted ASVS level for this application.', null=True),
        ),
        migrations.DeleteModel(
            name='ApplicationFileUpload',
        ),
        migrations.DeleteModel(
            name='ExternalRequest',
        ),
        migrations.AddField(
            model_name='applicationcustomfieldvalue',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boh.Application'),
        ),
        migrations.AddField(
            model_name='applicationcustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boh.CustomField'),
        ),
        migrations.AddField(
            model_name='application',
            name='custom_fields',
            field=models.ManyToManyField(through='boh.ApplicationCustomFieldValue', to='boh.CustomField'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationcustomfieldvalue',
            unique_together=set([('application', 'custom_field', 'value')]),
        ),
    ]
