# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boh', '0006_v0_0_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='questionnaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='questionnaire_template',
            field=models.TextField(blank=True, help_text='A GoSDL JSON format questionnaire'),
        ),
    ]
